const a =
{
  contratList: [{
    name: 'tst1',
    address: '0x808a5E5Bf0910343a5a2aea290c664A188E8889C',
    abi: [{
      constant: true,
      inputs: [],
      name: 'name',
      outputs: [{ name: '', type: 'string', value: 'test1' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
      signature: '0x06fdde03',
    }, {
      constant: false,
      inputs: [{ name: '_spender', type: 'address' }, { name: '_value', type: 'uint256' }],
      name: 'approve',
      outputs: [{ name: 'success', type: 'bool' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
      signature: '0x095ea7b3',
    }, {
      constant: true,
      inputs: [],
      name: 'totalSupply',
      outputs: [{ name: '', type: 'uint256', value: '999999000000000000000000' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
      signature: '0x18160ddd',
    }, {
      constant: false,
      inputs: [{ name: '_from', type: 'address' }, { name: '_to', type: 'address' }, { name: '_value', type: 'uint256' }],
      name: 'transferFrom',
      outputs: [{ name: 'success', type: 'bool' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
      signature: '0x23b872dd',
    }, {
      constant: true,
      inputs: [],
      name: 'decimals',
      outputs: [{ name: '', type: 'uint8', value: '18' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
      signature: '0x313ce567',
    }, {
      constant: false,
      inputs: [{ name: '_value', type: 'uint256' }],
      name: 'burn',
      outputs: [{ name: 'success', type: 'bool' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
      signature: '0x42966c68',
    }, {
      constant: true,
      inputs: [],
      name: 'standard',
      outputs: [{ name: '', type: 'string', value: 'https://mshk.top' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
      signature: '0x5a3b7e42',
    }, {
      constant: true,
      inputs: [{ name: '', type: 'address' }],
      name: 'balanceOf',
      outputs: [{ name: '', type: 'uint256' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
      signature: '0x70a08231',
    }, {
      constant: false,
      inputs: [{ name: '_from', type: 'address' }, { name: '_value', type: 'uint256' }],
      name: 'burnFrom',
      outputs: [{ name: 'success', type: 'bool' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
      signature: '0x79cc6790',
    }, {
      constant: true,
      inputs: [],
      name: 'symbol',
      outputs: [{ name: '', type: 'string', value: 'TST1' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
      signature: '0x95d89b41',
    }, {
      constant: false,
      inputs: [{ name: '_to', type: 'address' }, { name: '_value', type: 'uint256' }],
      name: 'transfer',
      outputs: [],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
      signature: '0xa9059cbb',
    }, {
      constant: false,
      inputs: [{ name: '_spender', type: 'address' }, { name: '_value', type: 'uint256' }, {
        name: '_extraData',
        type: 'bytes',
      }],
      name: 'approveAndCall',
      outputs: [{ name: 'success', type: 'bool' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
      signature: '0xcae9ca51',
    }, {
      constant: true,
      inputs: [{ name: '', type: 'address' }, { name: '', type: 'address' }],
      name: 'allowance',
      outputs: [{ name: '', type: 'uint256' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
      signature: '0xdd62ed3e',
    }, {
      inputs: [{
        name: 'initialSupply',
        type: 'uint256',
        index: 0,
        typeShort: 'uint',
        bits: '256',
        displayName: 'initial Supply',
        template: 'elements_input_uint',
        value: '999999',
      }, {
        name: 'tokenName',
        type: 'string',
        index: 1,
        typeShort: 'string',
        bits: '',
        displayName: 'token Name',
        template: 'elements_input_string',
        value: 'test1',
      }, {
        name: 'tokenSymbol',
        type: 'string',
        index: 2,
        typeShort: 'string',
        bits: '',
        displayName: 'token Symbol',
        template: 'elements_input_string',
        value: 'TST1',
      }], payable: false, stateMutability: 'nonpayable', type: 'constructor', signature: 'constructor',
    }, {
      anonymous: false,
      inputs: [{ indexed: true, name: 'from', type: 'address' }, {
        indexed: true,
        name: 'to',
        type: 'address',
      }, { indexed: false, name: 'value', type: 'uint256' }],
      name: 'Transfer',
      type: 'event',
      signature: '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
    }, {
      anonymous: false,
      inputs: [{ indexed: true, name: 'from', type: 'address' }, { indexed: false, name: 'value', type: 'uint256' }],
      name: 'Burn',
      type: 'event',
      signature: '0xcc16f5dbb4873280815c1ee09dbd06736cffcc184412cf7a71a0fdb75d397ca5',
    }],
    owneraddress: '0x2994d4112C1859eeefF606454b9D9b5C68B90B55',
    ownerpassword: '123456',
  }],
};
const b = JSON.stringify(a);
console.log(b);
